### ISSUE TITLE
window_group.hpp missing atomic include

### ISSUE THREAD

**Issue by benkonz** [giorgiomarcias/glfwm#2]
Hi everyone, I just checked out the project and built it with mingw32-make generated from cmake and the build failed because doPoll is of type std::atomic<bool>, but there is no defenition of atomic since atomic is never included in the file. doLoop has the same problem. I went ahead and added an #include <atomic> to the top of the file and everything compiled like normal.

**Comment by giorgiomarcias** [comment]
Hi, thanks for reporting it. I'd appreciate it if you could make a pull request with that `#include`.

**Comment by giorgiomarcias** [comment]
Solved with commit [298a7a2](https://github.com/giorgiomarcias/glfwm/commit/298a7a2b0638eb15bd0356ba3263f4b2cd4ef992).
