### ISSUE TITLE
mixed cases in the include directory

### ISSUE THREAD

**Issue by csukuangfj** [giorgiomarcias/glfwm#4]
Both glfwm and GLFWM are used, which has problems in Linux and Mac OS X systems.

glfwm: https://github.com/giorgiomarcias/glfwm/tree/master/include/glfwm

GLFWM:
 - https://github.com/giorgiomarcias/glfwm/blob/master/CMakeLists.txt#L62
 - and other header files, such as https://github.com/giorgiomarcias/glfwm/blob/master/include/glfwm/enums.hpp#L17

**Comment by giorgiomarcias** [comment]
Hi,
I can't reproduce any problem on Mac OS X. Could you give me more information, please?
What OS, compiler and cmake version?

Anyway, there shouldn't be name paths conflicting (`glfwm/` and `glfwm/include/GLFWM/` are different paths).
Have you installed it on your system?

**Comment by csukuangfj** [comment]
@giorgiomarcias 

I have cloned the repository to the directory `/tmp/kuangfn`.

Here are some logs:

```
/tmp/kuangfn/glfwm$ mkdir build
/tmp/kuangfn/glfwm$ cd build/
/tmp/kuangfn/glfwm/build$ cmake ..
-- The CXX compiler identification is GNU 4.9.2
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
CMake Error at CMakeLists.txt:88 (add_library):
  Cannot find source file:

    /tmp/kuangfn/glfwm/include/GLFWM/common.hpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx


-- Build files have been written to: /tmp/kuangfn/glfwm/build
```

The error occurs because of this line
<https://github.com/giorgiomarcias/glfwm/blob/master/CMakeLists.txt#L62>
which set the folder name to `GLFWM`, but the actual directory name is `glfwm`.

```
/tmp/kuangfn/glfwm/build$ cd ../include/
/tmp/kuangfn/glfwm/include$ ln -s glfwm/ GLFWM
/tmp/kuangfn/glfwm/include$ cd -
/tmp/kuangfn/glfwm/build
/tmp/kuangfn/glfwm/build$ cmake ..
-- Configuring done
-- Generating done
-- Build files have been written to: /tmp/kuangfn/glfwm/build
```

solves this problem.


As far as I know, both Mac OS and Linux are case sensitive while handling path names.
I am wondering why it has no problems on your Mac.

**Comment by csukuangfj** [comment]
Then refer to https://github.com/giorgiomarcias/glfwm/issues/6

**Comment by giorgiomarcias** [comment]
Ok, the problem was due to git that was case insensitive.
Commit [298a7a2](https://github.com/giorgiomarcias/glfwm/commit/298a7a2b0638eb15bd0356ba3263f4b2cd4ef992?diff=split) solves
