### ISSUE TITLE
The installed cmake configuration files do not export the header paths

### ISSUE THREAD

**Issue by csukuangfj** [giorgiomarcias/glfwm#5]
The provided CMakeLists.tx file https://github.com/giorgiomarcias/glfwm/blob/master/examples/simple_with_install/CMakeLists.txt

does not include the header path for GLFWM/glfwm.hpp.

It has to manually add the path to the include directories.

**Comment by giorgiomarcias** [comment]
Hi, that example is supposed to be compiled with GLFWM installed in your system.
That is, you should already have typed (supposing your current directory is the root of GLFWM):
```
cmake .
make && make install
```
then, you type:
```
cd examples/simple_with_install
cmake .
make
./glfwmExample
```

The needed paths are configured by cmake:
[https://github.com/giorgiomarcias/glfwm/blob/29f31a9f35c738befa596e31218c59e10a60b61e/examples/simple_with_install/CMakeLists.txt#L18](https://github.com/giorgiomarcias/glfwm/blob/29f31a9f35c738befa596e31218c59e10a60b61e/examples/simple_with_install/CMakeLists.txt#L18)
and
[https://github.com/giorgiomarcias/glfwm/blob/29f31a9f35c738befa596e31218c59e10a60b61e/examples/simple_with_install/CMakeLists.txt#L28](https://github.com/giorgiomarcias/glfwm/blob/29f31a9f35c738befa596e31218c59e10a60b61e/examples/simple_with_install/CMakeLists.txt#L28)

**Comment by csukuangfj** [comment]
@giorgiomarcias 

Yes, you are right. But it only solves the problem for linking the library.

If GLFWM is not installed in the default directory, as not everyone has the write permission to change `/usr/include`,  `find_package` cannot help to find 

```
#include <GLFWM/glfwm.hpp>
```
where the header file is.

I have to manually add `include_directories` with the absolute installation path to the `CMakeLists.txt`

It would be better if `find_package` returns some predefined variables like
`GLFWM_INCLUDE_DIR` and `GLFWM_LIBRARAY`.

**Comment by giorgiomarcias** [comment]
As for issue [#4](https://github.com/giorgiomarcias/glfwm/issues/4), commit [298a7a2](https://github.com/giorgiomarcias/glfwm/commit/298a7a2b0638eb15bd0356ba3263f4b2cd4ef992) solves also this one.
